name: Download File and Commit

on:
  schedule:
    #- cron: '0 */4 * * *'  # Запуск каждые 4 часа (можно настроить по вашему усмотрению)
    - cron: '*/10 * * * *'
  workflow_dispatch:  # Позволяет запускать вручную через интерфейс GitHub

jobs:
  download-and-commit:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Укажите нужную версию Python

      # Шаг 3: Устанавливаем зависимости
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Шаг 4: Запускаем скрипт для скачивания файла
      - name: Run download script
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: python download_script.py

      # Шаг 5: Настраиваем Git
      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      # Шаг 6: Добавляем и коммитим изменения
      - name: Commit and push changes
        run: |
          git add downloads/*
          git commit -m "Add downloaded file" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
